language: cpp

cache: ccache

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      install:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
      - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      before_script:
      - export CMAKE=cmake
      before_deploy:
      - git tag "$TRAVIS_BRANCH-v$TRAVIS_BUILD_NUMBER"
      - cd ${TRAVIS_BUILD_DIR}/build/bin
      - zip -r "$TRAVIS_BRANCH-$TRAVIS_OS_NAME-v$TRAVIS_BUILD_NUMBER.zip" Vita3K.app
      deploy:
        provider: releases
        api_key:
          secure: CJw/loFdyWhCo+oEVhFdERH0PJTKbOkxYqgStJ0VQnNKMUl3+EZkCbEjggxV7vM6C+IMxVUIX/HPV36LLdKE0LLjRYpC//UzZ5fScNVxUZXKi66m7DZjFx59FwCkcP/RrHfJnVGDjwg92k+RT2PDRcZbk7LvDAdrxi7qQTgqXXxPkNDbZ/9R0jUWg+N0s0XEas0MO4dQGsq9nIWp/djMjuGTOhtIkqD2jiP0i/JQgsXyJdFuNZTuBUl1t5NFPVO5hfR9eF/2NWKUgnadpilRTmJ8zN5joNFZYroZWUSxvy849cy0x+H1fvk6x8LmjS8Ew5gipZ73PIOfgq3QM+WNysW345qphiMKFI6NwDTz6JgxvooDVDrMwV5cc7qracqjKnjjtkkrJ/zNHh0SCiO1gFHOe9aBo+7QTKVpgTJM4Qn4B6tMpwKtUfeKRhIUBjBlvTXgifJTzI86eSz+BdfGaVFGqz1KGWRGijw93YGEl3KMEMf5FZhnvfpSi+6FyELE2+Ca9fW9XmN0S5zPojMQGQ+HSjrmq5xPAPopvuO7OR9XdXoaoQGIC20vzMPb/0VE/rC8hrA8ZyylTnv7u51/SN2p2HXysoIyOBjfNuDnjEUVPm2uPmvX/76XqRTA9Uxj4PFuXZO0/Rt8UvgdQE4Cvu7AE+fJMRgH6miBRFZ2i60=
        file: "$TRAVIS_BRANCH-$TRAVIS_OS_NAME-v$TRAVIS_BUILD_NUMBER.zip"
        skip_cleanup: true
        on:
          branch: format
          repo: pent0/Vita3K
      script: bash $TRAVIS_BUILD_DIR/.travis/macos/build.sh
    - os: linux
      sudo: required
      services: docker
      script: bash $TRAVIS_BUILD_DIR/.travis/linux/build.sh
      before_deploy:
      - git tag "$TRAVIS_BRANCH-v$TRAVIS_BUILD_NUMBER"
      - sudo chown -R travis:travis ${TRAVIS_BUILD_DIR}
      - cd ${TRAVIS_BUILD_DIR}/build/bin
      - zip -r "$TRAVIS_BRANCH-$TRAVIS_OS_NAME-v$TRAVIS_BUILD_NUMBER.zip" .
      deploy:
        provider: releases
        api_key:
          secure: CJw/loFdyWhCo+oEVhFdERH0PJTKbOkxYqgStJ0VQnNKMUl3+EZkCbEjggxV7vM6C+IMxVUIX/HPV36LLdKE0LLjRYpC//UzZ5fScNVxUZXKi66m7DZjFx59FwCkcP/RrHfJnVGDjwg92k+RT2PDRcZbk7LvDAdrxi7qQTgqXXxPkNDbZ/9R0jUWg+N0s0XEas0MO4dQGsq9nIWp/djMjuGTOhtIkqD2jiP0i/JQgsXyJdFuNZTuBUl1t5NFPVO5hfR9eF/2NWKUgnadpilRTmJ8zN5joNFZYroZWUSxvy849cy0x+H1fvk6x8LmjS8Ew5gipZ73PIOfgq3QM+WNysW345qphiMKFI6NwDTz6JgxvooDVDrMwV5cc7qracqjKnjjtkkrJ/zNHh0SCiO1gFHOe9aBo+7QTKVpgTJM4Qn4B6tMpwKtUfeKRhIUBjBlvTXgifJTzI86eSz+BdfGaVFGqz1KGWRGijw93YGEl3KMEMf5FZhnvfpSi+6FyELE2+Ca9fW9XmN0S5zPojMQGQ+HSjrmq5xPAPopvuO7OR9XdXoaoQGIC20vzMPb/0VE/rC8hrA8ZyylTnv7u51/SN2p2HXysoIyOBjfNuDnjEUVPm2uPmvX/76XqRTA9Uxj4PFuXZO0/Rt8UvgdQE4Cvu7AE+fJMRgH6miBRFZ2i60=       
        file: "$TRAVIS_BRANCH-$TRAVIS_OS_NAME-v$TRAVIS_BUILD_NUMBER.zip"
        skip_cleanup: true
        on:
          branch: format
          repo: pent0/Vita3K

branches:
  except:
    - "/master-v[0-9]/"
